In [2]:
import pandas as pd #자료의 데이터프레임화
import random #타임슬립에 랜덤숫자적용
import time #타입슬립
import json #파일저장
#인스타그램 접속
from random_user_agent.params import SoftwareName, OperatingSystem 
from random_user_agent.user_agent import UserAgent
#웹드라이버 및 화면조종
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import ElementClickInterceptedException
from selenium.webdriver.common.by import By #로딩함수에 적용
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys

# from eunjeon import Mecab
import unicodedata #이모티콘
# import pyodbc
import re #문자분류
import collections 
class IG_Bot:
    '''로봇처럼 보이기 방지'''
    
    def __init__(self, username, password):
        software_names= [SoftwareName.CHROME.value]
        operating_systems=[OperatingSystem.WINDOWS.value]
        
        #Randomized User ID
        user_agent_rotator= UserAgent(software_name = software_names,
                                     operating_systems=operating_systems,
                                     limit=100)
        user_agent= user_agent_rotator.get_random_user_agent()
        chrome_options=Options()
#         chrome_options.add_argument("--headless")
        chrome_options.add_argument("--no-sendbox")
        chrome_options.add_argument("--disable-gpu")
        chrome_options.add_argument(f'user-agent={user_agent}')
        path='c:\python_temp\chromedriver.exe'
        
        cookies_file_path='c:\IG\cookies.json'
        cookie_websites=['https://instagram.com']
        self.cookies_file_path= cookies_file_path
        self.cookie_websites= cookie_websites
        self.driver=webdriver.Chrome(chrome_options=chrome_options,executable_path=path)
        
        self.driver.get('https://instagram.com')
        
        time.sleep(1.5)

        try:
            cookies=json.load(open(self.cookies_file_path,'rb'))
            for website in self.cookie_websites:
                for cookie in cookies:
                    self.driver.add_cookie(cookie)
                self.driver.refresh()
        except Exception as e:
            print(str(e))
       
    def loading(self,xpath):
        '''페이지로딩 기다리기'''
        WebDriverWait(self.driver,60).until(EC.presence_of_element_located((By.XPATH,xpath)))
    
    def save_cookies(self):
        '''쿠키저장'''
        json.dump(self.driver.get_cookies(),open('c:\IG\cookies.json','w'))
    
    def load_cookies(self):
        '''쿠키로드'''
        cookies= json.load(open('cookies.json','rb'))
        for cookie in cookies:
            self.driver.add_cookie(cookie)
    
    def login(self):
        '''로그인'''
        try:
            self.driver.find_element_by_xpath('//*[@id="loginForm"]/div/div[1]/div/label/input').send_keys(username)
            self.driver.find_element_by_xpath('//*[@id="loginForm"]/div/div[2]/div/label/input').send_keys(password)
            self.loading('//*[@id="loginForm"]/div/div[3]')
            time.sleep(0.5)
            self.driver.find_element_by_xpath('//*[@id="loginForm"]/div/div[3]').click()
            self.loading('//*[@id="react-root"]/section/main/div/div/div/div/button')
            self.driver.find_element_by_xpath('//*[@id="react-root"]/section/main/div/div/div/div/button').click()
            self.loading('/html/body/div[5]/div/div/div/div[3]/button[2]')
            self.driver.find_element_by_xpath('/html/body/div[5]/div/div/div/div[3]/button[2]').click()
        except:
            self.loading('/html/body/div[5]/div/div/div/div[3]/button[2]')
            self.driver.find_element_by_xpath('/html/body/div[5]/div/div/div/div[3]/button[2]').click()

'''크롤러'''           
class Crawler(IG_Bot):
    global insta_dict
    global number
    ########################################숫자바꾸기#############################################
    number=1
    insta_dict=[]
    


    def run(self):
        continue_=True
        count=0
        query=input('검색어를 입력하시오. > ') 
        query=re.sub('[ ]','', query)
        self.driver.get('https://www.instagram.com/explore/tags/'+query)
        
        s_time=time.time()
        
        try:
            self.driver.find_element_by_xpath('/html/body/div[5]/div/div/div/div[3]/button[2]').click()
        except:
            pass
        time.sleep(0.5)
        self.loading('//*[@id="react-root"]/section/main/article/div[1]/div/div/div[1]/div[1]/a/div[1]/div[2]')
        
        self.driver.find_element_by_xpath('//*[@id="react-root"]/section/main/article/div[1]/div/div/div[1]/div[1]/a/div[1]/div[2]').click()
        while count<2000:
            self.crawl()
            
                                                #Acting like person by random
            time.sleep(random.randrange(0,5))
            try:
                self.driver.find_element_by_css_selector('div.l8mY4 ').click()
            
            except:
                continue_=False
            count+=1
            time.sleep(2)
            if continue_==False:
                break
        
        print('id 저장 개수 :{}개'.format(len(insta_dict['id'])))
        print('텍스트 저장 개수 :{}개'.format(len(insta_dict['text'])))

        e_time=time.time()
        (f'{e_time-s_time}초 걸렸습니다.')    
        
            
            
            ###################숫자바꾸기######################
  #페이지 스크랩핑  
    def crawl(self):
        global clean_text
        
        extract={"id": "IARW21", 
     "metadata": { "title": "휘뚜마뚜 웹문서 말뭉치 IARW21", 
                  "creator": "이재관", 
                  "distributor": "휘뚜마뚜", 
                  "year": "2021", 
                  "category": "인스타그램 > 술집", 
                  "annotation_level": [ "원시" ], 
                  "sampling": "텍스트 추출" }, 
     "document": {"metadata": { "title": "무제", 
                                 "author": "", 
                                 "date": "20211110" }, 
                    "content": {"text": ""}}
                }
        global number
        self.loading('/html/body/div[6]/div[2]/div/article')
             
            
        ## id 정보 수집
        try:
            info_id = self.driver.find_element_by_css_selector('h2._6lAjh').text
            extract['document']['metadata']['author']=info_id
        except:
            try:          
                info_id = self.driver.find_element_by_css_selector('div.C4VMK').text.split()[0]
                extract['document']['metadata']['author']=info_id
            except:  
                info_id = self.driver.find_element_by_css_selector('div.e1e1d').text
                extract['document']['metadata']['author']=info_id
        ## 시간정보 수집 
        uploadTime=self.driver.find_element_by_css_selector('time._1o9PC')
        time_info=uploadTime.get_attribute('datetime')[:19]
        extract['document']['metadata']['date']=time_info
        ##text 정보수집
        clean_text=''

        raw_info = self.driver.find_element_by_css_selector('div.C4VMK').text.split()
        raw_info = raw_info[1:len(raw_info)-1]
        text=[]
        ######################광고나 필요없는 단어 거르기############################

        stopword='''🌿 식물구매 및 상담: 카카오톡 @고포레스트
🌿 주소: 서울특별시 서초구 강남대로27#양재꽃시장가동8호
소망&고포레스트 (첫째주, 셋째주 일요일 휴무)
🌿 서울, 경기, 인천 등 수도권지역은 당일배송도 가능합니다. [🌿고포레스트🌿]
푸딩쓰  푸딩쓰맛집  푸딩쓰성수 ⏱
프로필 상단 카톡 id ID 문의 전화 오시는 길 전화번호 주차 DM 댓글 전화번호 주차여부 불가 추가정보 위치주소 문의전화 코로나 협찬 가맹문의
시간 번호 주소 위치 휴무 상호명 상호 영업시간 영업 <버려진 쇼파에 뿌리내린 식물>
-
부서지고 헤진, 망가지고 낡은, 오래되고 깨진,
찢어지고 하나가 없는, 구멍나고 조각난, 더럽고 텅빈
제대로 버려지지도 못해 과태료부과대상이 되어버린
몇가지 사물들 수제버거 빈티지 갬성 카페 릴리마를렌 🪴
밀크티에 치즈케이크~ 접시가 갬성있네 ☕
빈티지 갬성 좋아하시는 분들이 좋아하실듯! 네이버에서 도우넛 버거로 하도 핫하길래 방문했는데 너무 맛있자나~ 먹어본 사람들만 안다는 그집
숨은 골목에 숨은 맛집 혜화동버거 혜화동버거
맥도날드,롯데리아보다 나은듯
역시 이 맛은 수제버거를 따라갈수 없는 것인가?
솜씨 좋은 우리 #커플 고객님 👍👍
#최고다최고
#레터링케이크 직접 만들기 체험
 #케익아이메이드 와서 한개 먹고 매일 아쉬워서 두개먹고 유자차인 줄 알고 시켰는데 알고보니 유자생강차였다는
깔깔유머 어쩐지 속이 맵더라 …… 거지만 혜화동버거 먹으러
. 오븐에 있을 때가 가장 맛있어보이는 스콘들
오늘도 한가득 구워놓고 오픈했습니다! ◡̈

무화과 철이 지나면서 무화과 스콘의 앞날을 궁금해하시는 분들이 종종 계시는데요, 더블린에서는 건 무화과를 사용해 프리저브 잼을 만들고 있어 사계절 내내 만나실 수 있답니다 ( •◡-)✧˖° ♡

오늘도 더블린하세요 ☘️ 우연히 들린 #혜화동버거? 진짜 존맛탱이다 수제버거는 이제 여기서 먹어야겠다
- 말해뭐해 먹자 먹어 진짜 존맛탱 먹고 피식 ,,,
왜케 난 양식이 이렇게 맛있을까 ,, #대학로맛집#혜화역맛집#혜화맛집 저번에 주문했었는데 맛있더라고요~ ' 라고 말씀해주신 남자고객님^^ #감사합니다
#생딸기 가득 맛있는 생크림
#레터링케이크 #딸기케이크🍰 는 역시 맛집🔥
연극보고 맛있는 거 먹으러 가자구🤗
@@맛집 도장깨기 각❓
#대학로맛집 
. #을지로맛집 #을지로카페 #회기맛집 #경희대맛집 #성신여대카페 #종각맛집 #종각역맛집 #혜화역맛집 #익선동맛집 #익선동카페 #서촌맛집 #삼청동맛집
.
.
#동대문맛집 #성북구맛집 #종로맛집 #혜화맛집 #성신여대맛집 #대학로맛집  #인사동맛집 #경복궁맛집 #종로카페 #광화문맛집 #광화문카페 #
#조각케이크

○■ 딸기홀케이크  예약안내
3일전 가능 하시며
홀케이크 1호 34,000원 입니다.
맛있는 거 먹으러 가자구🤗
@@맛집 도장깨기 각❓
#대학로맛집
□■브루잉 리스트 수험생 모두의 앞날에
🌸꽃길만 가득하길~•~ #수능응원
ㅡ 파나마 돈벤지 게이샤 N , ASD
ㅡ 디카페인 콜롬비아 리브레 셀렉션
ㅡ 에티오피아  하마쇼W  맛집🔥
ㅡ 케냐 루타가티
응원합니다!👊🏻 똑같이 먹었는데도 살이찐다?
안먹었는데도 살이찐다?

그건 바로 👉🏻독소 문제

내 몸에 청소 한번 한다~
생각하고 해보세요😊

행복한 결과 얻으실 수 있어요❤️

홍여우 6년차
리더 홍여우나비
010.3179.8887 
□■ 원두리스트 🔸_ 2021.12. 03(금) 오후 7시
🔸_ 2021. 12. 04(토) 오후 3시, 6시
🔸_ 전주대학교
ㅡ 리볼버(블랜드) 강배전  
ㅡ 앤썸 (블랜드) 중배전 
ㅡ 디카페인 콜롬비아 리브레 셀렉션  중배전 그날이후, 사소한 순간도 소중해졌다
.
1인 작가로 상담부터 편안한 분위기에서
충분한 대화로 만족스러운 결과물을 이끌어드립니다
딱딱한 증명사진부터 자연스러움을 추구하는 가족사진,
전문가다움을 강조 할 수 있는 프로필사진까지
쉽고 재미 있을 수 있도록 진행합니다
.
(인스타그램에 모든 사진은 사전 동의를 얻었으며 띵똥~‼️ #쭈꾸미도사 먹을 시간입니다🔥
<대창+쭈꾸미+새우>를 한판에 조질수있는곳‼️
맛있는거에 맛있는거 더하면 어케,,,먹부림각
@쭈꾸미도사 신메뉴 쭈곱새 먹으러ㄱㄱ 역삼골목냉면의
도시락 배달 6:00
네이버 메인앱에서
첫발 .
음 . .재밋다 부산 남구 용소로13번길 30
화요일 - 금요일 19:30
토요일, 일요일 15:30 / 18:00
매주 월요일 없음
불법 사진 도용을 금지합니다)
''' 
        stopword=stopword.split(' ')

        for i in raw_info:

            if i in stopword:
                pass
            else:
                i=re.sub('[\U00010000-\U0010ffff!@#$%^&*()-=_+{}~''""<>/?]',' ',i)

                if i=='':
                    pass
                elif i in stopword:
                    pass
                else:               
                    text.append(i)
        clean_text = ' '.join(text)
        extract['document']['content']['text']=clean_text
        
        
    #일련번호
        if clean_text=='':
            pass
        else:
            s_number=str(number).zfill(8)
            extract['id']=extract['id'][:6]+s_number
            number+=1

            #insta_dict
            insta_dict.append(extract)
        
        '''c드라이브에 IG폴더 만들고 secret.txt 파일에 윗줄에 아이디 2번째줄에 비밀번호 입력'''    
if __name__=='__main__':
    "Main (runs through classes)"
    data=pd.read_csv('c:\IG\secret.txt',header=None)
    username=data.iloc[0][0]
    password=data.iloc[1][0]
    
    '''처음실행하고 쿠키저장'''
def first_login():     
    '''Check login to instagram and save cookies'''
    bot=IG_Bot(username,password)
    bot.login()
    bot.save_cookies()

    '''쿠키저장 후 크롤러 가동하기'''
def run_():
    # '''Crawler'''
    bot=Crawler(username,password)
    bot.run()
# first_login()
run_()

'''아래 셀은 쿠기 저장 예시'''

<ipython-input-2-12d14445c00e>:46: DeprecationWarning: use options instead of chrome_options
  self.driver=webdriver.Chrome(chrome_options=chrome_options,executable_path=path)


검색어를 입력하시오. > 대학로연극


TimeoutException: Message: 


In [3]:
insta_dict

[{'id': 'IARW2100000001',
  'metadata': {'title': '휘뚜마뚜 웹문서 말뭉치 IARW21',
   'creator': '이재관',
   'distributor': '휘뚜마뚜',
   'year': '2021',
   'category': '인스타그램 > 술집',
   'annotation_level': ['원시'],
   'sampling': '텍스트 추출'},
  'document': {'metadata': {'title': '무제',
    'author': 's0l_ppeu',
    'date': '2021-10-21T09:38:34'},
   'content': {'text': '[  ad ] \u2061 대학로 하면 연극  연극 하면 대학로죠   대학로 인기 연극 중 하나인  뮤지컬프리즌 에 초대받아서 보고 왔어요    \u2061 공연 중간중간 관객들과 소통하는 부분도 많고 울랄라세션 전 멤버셨던 하준석님을 비롯한 배우분들 노래 넘나 잘 하셔서 깜놀   \u2061 무엇보다 남자친구가 죄수번호    번역을 맡아 평생 잊지 못할 추억이 되었어요♫꒰･‿･๑꒱ 휴지도 감사합니다 ㅋㅋㅋ   \u2061 피드 속 영상은 스포입니다   꼭 넘겨서 보고 가세요 ✨ \u2061 \u2061  대학로연극  대학로뮤지컬  대학로데이트  대학로공연  프리즌뮤지컬  프리즌  뮤지컬프리즌  뮤지컬  연극  대학로연극추천  뮤지컬추천'}}},
 {'id': 'IARW2100000002',
  'metadata': {'title': '휘뚜마뚜 웹문서 말뭉치 IARW21',
   'creator': '이재관',
   'distributor': '휘뚜마뚜',
   'year': '2021',
   'category': '인스타그램 > 술집',
   'annotation_level': ['원시'],
   'sampling': '텍스트 추출'},
  'document': {'metadata': {'title': '무제',
    'author'

In [4]:
# 폴더 경로 설정 및 json 파일로 저장.
with open('c:\IG\IM1.json', 'w') as f:
    json.dump(insta_dict, f,indent=4)

In [4]:
#json 파일 로드
with open('c:\IG\sample.json','r') as f:
    json_file=json.load(f)

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\IG\\sample.json'

In [136]:
'''예시 아래 결과창'''

import pandas as pd
from selenium.webdriver.common.keys import Keys
def crawl(self):
    insta_dict = {'img':[],
                    'id':[],
                  'date': [],
                  'like': [],
                  'text': [],
                  'hashtag':[]}
    ## 이미지 수집

    try:
        srcs=driver.find_element_by_xpath('/html/body/div[6]/div[2]/div/article/div/div[1]/div/div/div/div/div/video')
        src=srcs.get_attribute('poster')
        insta_dirct['img'].append(src)
    except:
        src=driver.find_element_by_xpath('/html/body/div[6]/div[2]/div/article/div/div[1]/div/div[1]/div[2]/div/div/div/ul/li/div/div/div/div/img')
        src=src.get_attribute('src')
        insta_dict['img'].append(src)
    ## id 정보 수집
    try:
        info_id = driver.find_element_by_css_selector('h2._6lAjh').text
        insta_dict['id'].append(info_id)
    except:
        info_id = driver.find_element_by_css_selector('div.C4VMK').text.split()[0]
        insta_dict['id'].append(info_id)
    print(insta_dict['id'])
    print()


    ## 시간정보 수집 
    upload_time=driver.find_element_by_xpath('/html/body/div[6]/div[2]/div/article/div/div[2]/div/div[2]/div[2]/a/time')
    print(upload_time.get_attribute('title'))
    time_raw = driver.find_element_by_css_selector('time.FH9sR.Nzb55')
    time_info = pd.to_datetime(time_raw.get_attribute('datetime')).normalize()
    insta_dict['date'].append(time_info)
    print(insta_dict['date'])
    print()

    ## like 정보 수집
    try:
        check=driver.find_element_by_xpath('/html/body/div[6]/div[2]/div/article/div/div[2]/div/div[2]/section[2]/div/span/span')
        
    except:
        try:
            like=driver.find_element_by_xpath('/html/body/div[6]/div[2]/div/article/div/div[2]/div/div[2]/section[2]/div/div/a/span')
            insta_dict['like'].append(like)
            
        except:
            id=[]
            driver.find_element_by_xpath('/html/body/div[6]/div[2]/div/article/div/div[2]/div/div[2]/section[2]/div/div[2]/a[2]').click()
            while True:
                last_height =driver.find_element_by_xpath('/html/body/div[7]/div/div/div[3]/div/div/div/div/div/div/span/a').location

                c=driver.find_elements_by_xpath('/html/body/div[7]/div/div/div[3]/div/div/div/div/div/div/span/a')

                for i in c:  
                    if i.text not in id:
                        id.append(i.text)     
                    else:
                        pass
                
                driver.find_element_by_css_selector('div._1XyCr').click()
                driver.find_element_by_css_selector('body').send_keys(Keys.PAGE_DOWN)
                driver.find_element_by_css_selector('body').send_keys(Keys.PAGE_DOWN)
                driver.find_element_by_css_selector('body').send_keys(Keys.PAGE_DOWN)
                time.sleep(1)
                new_height =driver.find_element_by_xpath('/html/body/div[7]/div/div/div[3]/div/div/div/div/div/div/span/a').location

                if last_height==new_height:
                    driver.find_element_by_xpath('/html/body/div[7]/div/div/div[1]/div/div[2]/button').click()
                    break

            like=len(id)
            insta_dict['like'].append(like)

    ##text 정보수집
    raw_info = driver.find_element_by_css_selector('div.C4VMK').text.split()
    raw_info = raw_info[1:len(raw_info)-1]
    text=[]
    for i in raw_info:
        if '#' in i:
            pass
        else:
            text.append(i)
    clean_text = ' '.join(text)
    text.append(clean_text)
    insta_dict['text'].append(text)



    ##hashtag 수집
    raw_tags = driver.find_elements_by_css_selector('a.xil3i')
    hash_tag = []
    for i in raw_tags:
        hash_tag.append(i.text)
    insta_dict['hashtag'].append(hash_tag)

https://scontent-gmp1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/239218352_335498761650611_1251356593086644312_n.jpg?_nc_ht=scontent-gmp1-1.cdninstagram.com&_nc_cat=111&_nc_ohc=G78EYJ1SFPMAX_B6Pku&edm=AP_V10EBAAAA&ccb=7-4&oh=76b23c271d1ea87146c2781573ac94fe&oe=616D2144&_nc_sid=4f375e
['hello_storylibrary']

2021년 8월 20일
[Timestamp('2021-08-20 00:00:00+0000', tz='UTC')]

26

["[스토리라이브러리만의 특별한 영화 추천, 스라의 빛✨소개] 🎬 너무 좋아서 벽치다가 무너져서 🎬 옆집 만날 장르?! 🎬 말이 필요없는 망작?! 🎬 꿈에 나올것 같았던 영화?! 🎬 간단하게 보기 좋은 영화?! 🎬 꿈인지 현실인지 헷갈리는 영화?! 스라러 재영이 만들어준 영화 추천 큐레이션 게시판, '스라의 빛' 반응이 핫해요! 이미 있는 영화 장르를 제외하고 새로운 장르와 장르에 어울리는 영화를 추천하는 게시판이에요. 게시판이 생긴지 한달도 되지 않아서 어느새 빼곡히 추천 장르, 영화로 가득찼어요. 하루 하루 스라러들이 슬쩍 남겨주고 간 흔적을 읽어보는 재미가 쏠쏠해요. 새로운 영화를 살펴보며 낯선 영감을 만나고 싶다면 스라로 놀러오세요! 오늘도 스토리라이브러리 문 활-짝! 저녁 6시까지 문을 열어둘께요. 9월부터는 수, 목, 금요일은 오후 5시부터 저녁 9시까지, 주말엔 오후 12시부터 6시까지 문을 열어요! 놀러오고 싶다면 프로필 링크를 클릭👆"]

['#스토리라이브러리', '#스라', '#스라러', '#스라의빛', '#영화', '#영화추천', '#장르', '#장르추천', '#1219세전용작업실', '#혜화역2번출구']


In [54]:
import re
a='🎬 너무 좋아서 벽치다가 무너져서 ###🎬 ####옆#집# 만날 장르?! 🎬 말이 필요없는 망작?! 🎬 꿈에 나올것 같았던 영화?! 🎬 '
b=re.sub('[\U00010000-\U0010ffff!@#$%^&*()-=_+{}~''""<>/?]',' ',a)


print(b)
b.split()

  너무 좋아서 벽치다가 무너져서          옆 집  만날 장르     말이 필요없는 망작     꿈에 나올것 같았던 영화     


['너무',
 '좋아서',
 '벽치다가',
 '무너져서',
 '옆',
 '집',
 '만날',
 '장르',
 '말이',
 '필요없는',
 '망작',
 '꿈에',
 '나올것',
 '같았던',
 '영화']

In [60]:
import numpy as np
EMBEDDING_DIM = 10
VOCAB_SIZE=4
embedding_matrix = np.zeros((VOCAB_SIZE, EMBEDDING_DIM))
print(embedding_matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
